export const ENDPOINTS = {
  AUTH: {
    REGISTER: "/auth/register",
    LOGIN: "/auth/login",
    ME: "/auth/me",
    REFRESH: "/auth/refresh",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    CHANGE_PASSWORD: "/auth/change-password",
    LOGOUT: "/auth/logout",
  },
  USERS: {
    BASE: "/users",
    BY_ID: (id: string) => `/users/${id}`,
  },
  HEALTH: {
    BASE: "/health",
  },
    STUDENTS: {
    DASHBOARD: "/student/dashboard",
    REGISTER: "/student/register",
    REGISTER_ME: "/student/register/me",
    REGISTER_ADMIN: "/student/register/admin",
    REGISTER_BY_ID: (id: string) => `/student/register/${id}`,
    REGISTER_DOWNLOAD: (id: string) => `/student/register/${id}/download`,
  },
    INTERNSHIPS: {
    BASE: "/internships",
    BY_ID: (id: string) => `/internships/${id}`,
    APPLY: (id: string) => `/internships/${id}/apply`,
    ENROLL: (id: string) => `/internships/${id}/enroll`,
    MY_APPLICATIONS: "/internships/applications/my-applications",
    APPROVE_POSTING: (id: string) => `/internships/${id}/approve-posting`,
    REJECT_POSTING: (id: string) => `/internships/${id}/reject-posting`,
    APPLICATIONS: (id: string) => `/internships/${id}/applications`,
    EXPORT_APPLICATIONS: (id: string) =>
      `/internships/${id}/applications/export`,
    PENDING: "/internships/pending",
  },
    ENROLLMENTS: {
    MY_ENROLLMENTS: "/enrollments/my-enrollments",
    ID_CARD: (id: string) => `/enrollments/${id}/id-card`,
    COMPLETE: (id: string) => `/enrollments/${id}/complete`,
    ISSUE_CERTIFICATE: (id: string) => `/enrollments/${id}/issue-certificate`,
    SUBMISSIONS: (id: string) => `/enrollments/${id}/submissions`,
    SUBMISSION_BY_ID: (id: string, submissionId: string) =>
      `/enrollments/${id}/submissions/${submissionId}`,
  },
    CERTIFICATES: {
    MY_CERTIFICATES: "/certificates/my-certificates",
    DOWNLOAD: (id: string) => `/certificates/${id}/download`,
    GRADE: (id: string) => `/certificates/${id}/grade`,
  },
    PAYMENTS: {
    MY_PAYMENTS: "/payments/my-payments",
    RECEIPT: (id: string) => `/payments/${id}`,
    CREATE_ORDER: "/payments/create-order",
    VERIFY_SIGNATURE: "/payments/verify-signature",
    REFUND: "/payments/refund",
    ADMIN_LIST: "/payments",
    WEBHOOK: "/payments/webhook",
  },
    TICKETS: {
    BASE: "/tickets",
    MY_TICKETS: "/tickets/my-tickets",
    BY_ID: (id: string) => `/tickets/${id}`,
  },
    NOTICES: {
    BASE: "/notices",
    BY_ID: (id: string) => `/notices/${id}`,
  },
    INSTRUCTOR: {
    REGISTER: "/instructor/register",
    REGISTER_ME: "/instructor/register/me",
    REGISTER_ADMIN: "/instructor/register/admin",
    REGISTER_BY_ID: (id: string) => `/instructor/register/${id}`,
    IMMERSIONS: "/instructor/immersions",
    IMMERSION_ACCEPT: (id: string) => `/instructor/immersions/${id}/accept`,
    IMMERSION_REJECT: (id: string) => `/instructor/immersions/${id}/reject`,
    SUBMISSIONS: "/instructor/submissions",
    SUBMISSIONS_GRADE: (id: string) => `/instructor/submissions/${id}/grade`,
    DASHBOARD: "/instructor/dashboard",
    PROFILE: "/instructor/profile",
    PROFILES_PENDING: "/instructor/profiles/pending",
    PROFILES_APPROVE: (id: string) => `/instructor/profiles/${id}/approve`,
    PROFILES_REJECT: (id: string) => `/instructor/profiles/${id}/reject`,
    MY_INTERNSHIPS: "/instructor/my-internships",
    MY_STUDENTS: "/instructor/my-students",
    ID_CARD: "/instructor/id-card",
    DOWNLOAD_ID_CARD: "/instructor/id-card/download",
    APPROVE_APPLICATION: (id: string, appId: string) =>
      `/internships/${id}/applications/${appId}/approve`,
    REJECT_APPLICATION: (id: string, appId: string) =>
      `/internships/${id}/applications/${appId}/reject`,
    RUNNING_INTERNSHIPS: "/internships",
  },
    EMERSION: {
    REGISTER: "/immersion/register",
    DASHBOARD: "/immersion-participant/dashboard",
    PROFILE: "/immersion-participant/profile",
    APPLICATION: "/immersion-participant/application",
    APPLICATION_MY: "/immersion-participant/application/my",
    APPLICATION_STATUS: "/immersion-participant/application-status",
    APPLICATION_DOWNLOAD: "/immersion-participant/application/download",
    CERTIFICATES: {
      MY: "/immersion/certificates/my",
      DOWNLOAD: (id: string) => `/immersion/certificates/${id}/download`,
      GRADE: (id: string) => `/immersion/certificates/${id}/grade`,
    },
    ID_CARD: {
      MY: "/immersion-participant/id-card",
      BY_APPLICATION_ID: (id: string) =>
        `/immersion/applications/${id}/id-card`,
      DOWNLOAD: (id: string) => `/immersion-id-cards/${id}/download`,
    },
    PAYMENTS: {
      MY_PAYMENTS: "/immersion/payments/my-payments",
      RECEIPT: (id: string) => `/immersion/payments/${id}`,
      CREATE_ORDER: "/immersion/payments/create-order",
      VERIFY_SIGNATURE: "/immersion/payments/verify-signature",
      REFUND: "/immersion/payments/refund",
    },
    PROGRAMS: {
      LIST: "/immersion",
      APPLY: (id: string) => `/immersion/programs/${id}/apply`,
    },
  },
  RECRUIT: {
    REGISTER: "/recruit-user/register",
    PROFILE: "/recruit-user/profile",
    APPLICATIONS: "/recruit-user/applications",
    APPLICATION_BY_ID: (id: string) => `/recruit-user/applications/${id}`,
    APPLICATION_PDF: (id: string) => `/recruit-user/applications/${id}/pdf`,
    SETTINGS: "/recruit-user/settings",
    OPENINGS: "/recruit-user/openings",
    APPLY: (openingId: string) => `/recruit-user/openings/${openingId}/apply`,
    EDUCATION: "/recruit-user/profile/education",
    EDUCATION_BY_ID: (id: string) => `/recruit-user/profile/education/${id}`,
    EXPERIENCE: "/recruit-user/profile/experience",
    EXPERIENCE_BY_ID: (id: string) => `/recruit-user/profile/experience/${id}`,
    DOCUMENTS: "/recruit-user/profile/documents",
    REFERENCES: "/recruit-user/profile/references",
    REFERENCE_BY_ID: (id: string) => `/recruit-user/profile/references/${id}`,
    SPECIFIC_INFO: "/recruit-user/profile/specific-info",
  },
    SUPER_ADMIN: {
    RECRUIT_REGISTRATIONS: "/recruit-user/profile/admin",
    JOB_OPPORTUNITIES: "/job-opportunities",
    JOB_OPPORTUNITY_BY_ID: (id: string) => `/job-opportunities/${id}`,
    JOB_OPPORTUNITY_EXPORT_APPLICATIONS: (id: string) =>
      `/job-opportunities/${id}/applications/export`,
    JOB_APPLICATIONS: "/job-applications",
    JOB_APPLICATION_STATUS: (id: string) => `/job-applications/${id}/status`,
    MEDIA_PHOTOS: "/media/photos",
    MEDIA_PHOTOS_BY_ID: (id: string) => `/media/photos/${id}`,
    MEDIA_VIDEOS: "/media/videos",
    MEDIA_VIDEOS_BY_ID: (id: string) => `/media/videos/${id}`,
    MEDIA_NEWSPAPERS: "/media/newspapers",
    MEDIA_NEWSPAPERS_BY_ID: (id: string) => `/media/newspapers/${id}`,
    MEDIA_ONLINE_LINKS: "/media/online-links",
    MEDIA_ONLINE_LINKS_BY_ID: (id: string) => `/media/online-links/${id}`,
    BLOGS: "/blogs",
    BLOGS_BY_ID: (id: string) => `/blogs/${id}`,
    REVIEWS_PENDING: "/reviews/pending",
    REVIEW_APPROVE: (id: string) => `/reviews/${id}/approve`,
    REVIEW_BY_ID: (id: string) => `/reviews/${id}`,
    DONATIONS_ADMIN: "/donations/admin",
    DONATIONS_ADMIN_EXPORT: "/donations/admin/export",
    TICKETS_ADMIN: "/tickets/admin",
    IMMERSION_APPLICATIONS: "/immersion/applications",
    IMMERSION_APPLICATION_BY_ID: (id: string) =>
      `/immersion/applications/${id}`,
    IMMERSION_STATUS: (id: string) => `/immersion/applications/${id}/status`,
    IMMERSION_ASSIGN_MENTOR: (id: string) =>
      `/immersion/applications/${id}/assign-mentor`,
    IMMERSION_ISSUE_CERTIFICATE: (id: string) =>
      `/immersion/applications/${id}/issue-certificate`,
    IMMERSIONS: "/immersion",
    IMMERSIONS_BY_ID: (id: string) => `/immersion/${id}`,
    IMMERSION_EXPORT_APPLICATIONS: (id: string) =>
      `/immersion/${id}/applications/export`,
    IMMERSION_CATEGORIES: "/immersion/categories",
    LEAD_INTERESTS: (id: string) => `/internships/${id}/interests`,
    RUNNING_INTERNSHIPS: "/internships",
    RUNNING_INTERNSHIPS_BY_ID: (id: string) => `/internships/${id}`,
  },
  REVIEWS: {
    MY_REVIEWS: "/reviews/my-reviews",
  },
  FEEDBACK: {
    BASE: "/feedback",
    MY_FEEDBACKS: "/feedback/my-feedbacks",
  },
  ID_CARDS: {
    BY_ID: (id: string) => `/id-cards/${id}`,
  },
};
